jobs:
- name: go_buildpack_pcfdev
  public: true
  serial: true
  plan:
  - aggregate:
    - get: buildpack-github-release
      resource: gh-release-go-buildpack
      params:
        globs:
          - "*cached*"
      trigger: true
    - put: env-info
      resource: local-env
      params: {acquire: true}
    - get: concourse-cloudfoundry-tasks
  - task: upload-go-buildpack
    file: concourse-cloudfoundry-tasks/ci/updatebuildpack/updatebuildpack.yml
    params:
      BUILDPACK_NAME: go_buildpack
    on_failure:
      put: env-info
      resource: local-env
      params: {release: env-info}



- name: smoketest-sandbox
  public: true
  serial: true
  plan:
  - aggregate:
    - get: smoke-test
      resource: cf-smoke-test
    - get: gh-release-go-buildpack
      trigger: true
      passed: [go_buildpack_pcfdev]
    - get: env-info
      resource: local-env
    - get: concourse-cloudfoundry-tasks
  - task: smoke-test
    file: concourse-cloudfoundry-tasks/ci/smoketest/smoketest.yml
    on_failure:
      put: env-info
      resource: local-env
      params: {release: env-info}


- name: acceptance-sandbox
  public: true
  serial: true
  plan:
  - aggregate:
    - get: acceptance-tests
      resource: cf-acceptance-tests
    - get: gh-release-go-buildpack
      trigger: true
      passed: [smoketest-sandbox]
    - get: env-info
      resource: local-env
    - get: concourse-cloudfoundry-tasks 
  - task: acceptance-tests
    file: concourse-cloudfoundry-tasks/ci/acceptancetests/acceptancetests.yml
    ensure:
      put: env-info
      resource: local-env
      params: {release: env-info}




resources:
- name: local-env
  type: pool
  source:
    uri: git@github.com:shinji62/pool-concourse-config.git
    branch: master
    pool: local
    private_key: {{private-key-github-concourse}}


  #go buildpack
- name: gh-release-go-buildpack
  type: github-release
  source:
    user: cloudfoundry
    repository: go-buildpack
    access_token: {{github-access-token}}



#Cloudfoundry /smoke test
- name: cf-smoke-test
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-smoke-tests.git
    branch: master
    private_key: {{private-key-github-concourse}}



#Cloudfoundry / Acceptance test
- name: cf-acceptance-tests
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-acceptance-tests.git
    branch: master
    private_key: {{private-key-github-concourse}}


#Common script repository
- name: concourse-cloudfoundry-tasks
  type: git
  source:
    uri: git@github.com:shinji62/concourse-cloudfoundry-tasks.git
    branch: master
    private_key: {{private-key-github-concourse}}


