jobs:

- name: smoketest-sandbox
  public: true
  serial: true
  plan:
  - aggregate:
    - get: smoke-test
      resource: cf-smoke-test
    - get: gh-release-php-buildpack
      trigger: true
    - get: env-info
      resource: gh-env-config-pcfdev
      trigger: true
  - task: build-binary
    file: firehose-to-syslog-ci/ci/build-all/build-all.yml
    params:
      VERSION_APP: version/number


     




resource_types:


#php  
- name: gh-release-php-buildpack
  type: github-release
  source:
    user: cloudfoundry
    repository: php-buildpack
    access_token: {{}}



#Env Resource pcfdev
- name: gh-env-config-pcfdev
  type: git
  source:
    uri: git@github.com:shinji62/env-config.git
    branch: pcfdev

- name:
  type:
  source:
    uri:
    branch: master


#Cloudfoundry /smoke test
- name: cf-smoke-test
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-smoke-tests.git
    branch: master

    




