jobs:
- name: php_buildpack_pcfdev
  public: true
  serial: true
  plan:
  - aggregate:
    - get: buildpack-github-release
      resource: gh-release-php-buildpack
      params:
        globs:
          - "*cached*"
      trigger: true
    - get: env-info
      resource: gh-env-config-pcfdev
      trigger: true
    - get: buildpack-pipeline
  - task: upload-php-buildpack
    file: buildpack-pipeline/ci/updatebuildpack/updatebuildpack.yml
    params:
      BUILDPACK_NAME: php_buildpack


- name: ruby_buildpack_pcfdev
  public: true
  serial: true
  plan:
  - aggregate:
    - get: buildpack-github-release
      resource: gh-release-ruby-buildpack
      trigger: true
      params:
        globs:
          - "*cached*"
    - get: env-info
      resource: gh-env-config-pcfdev
      trigger: true
    - get: buildpack-pipeline
  - task: upload-ruby-buildpack
    file: buildpack-pipeline/ci/updatebuildpack/updatebuildpack.yml
    params:
      BUILDPACK_NAME: ruby_buildpack

- name: go_buildpack_pcfdev
  public: true
  serial: true
  plan:
  - aggregate:
    - get: buildpack-github-release
      resource: gh-release-go-buildpack
      params:
        globs:
          - "*cached*"
      trigger: true
    - get: env-info
      resource: gh-env-config-pcfdev
      trigger: true
    - get: buildpack-pipeline
  - task: upload-go-buildpack
    file: buildpack-pipeline/ci/updatebuildpack/updatebuildpack.yml
    params:
      BUILDPACK_NAME: go_buildpack

- name: nodejs_buildpack_pcfdev
  public: true
  serial: true
  plan:
  - aggregate:
    - get: buildpack-github-release
      resource: gh-release-nodejs-buildpack
      trigger: true
      params:
        globs:
          - "*cached*"
    - get: env-info
      resource: gh-env-config-pcfdev
      trigger: true
    - get: buildpack-pipeline
  - task: upload-nodejs-buildpack
    file: buildpack-pipeline/ci/updatebuildpack/updatebuildpack.yml
    params:
      BUILDPACK_NAME: nodejs_buildpack

- name: python_buildpack_pcfdev
  public: true
  serial: true
  plan:
  - aggregate:
    - get: buildpack-github-release
      resource: gh-release-python-buildpack
      trigger: true
      params:
        globs:
          - "*cached*"
    - get: env-info
      resource: gh-env-config-pcfdev
      trigger: true
    - get: buildpack-pipeline
  - task: upload-python-buildpack
    file: buildpack-pipeline/ci/updatebuildpack/updatebuildpack.yml
    params:
      BUILDPACK_NAME: python_buildpack

- name: staticfile_buildpack_pcfdev
  public: true
  serial: true
  plan:
  - aggregate:
    - get: buildpack-github-release
      resource: gh-release-staticfile-buildpack
      trigger: true
      params:
        globs:
          - "*cached*"
    - get: env-info
      resource: gh-env-config-pcfdev
      trigger: true
    - get: buildpack-pipeline
  - task: upload-static-buildpack
    file: buildpack-pipeline/ci/updatebuildpack/updatebuildpack.yml
    params:
      BUILDPACK_NAME: staticfile_buildpack


- name: binary_buildpack_pcfdev
  public: true
  serial: true
  plan:
  - aggregate:
    - get: buildpack-github-release
      resource: gh-release-binary-buildpack
      trigger: true
      params:
        globs:
          - "*cached*"
    - get: env-info
      resource: gh-env-config-pcfdev
      trigger: true
    - get: buildpack-pipeline
  - task: upload-binary-buildpack
    file: buildpack-pipeline/ci/updatebuildpack/updatebuildpack.yml
    params:
      BUILDPACK_NAME: binary_buildpack



- name: java_buildpack_pcfdev
  public: true
  serial: true
  plan:
  - aggregate:
    - get: buildpack-github-release
      resource: gh-release-java-buildpack
      trigger: true
      params:
        globs:
          - "*offline*"
    - get: env-info
      resource: gh-env-config-pcfdev
      trigger: true
    - get: buildpack-pipeline
  - task: upload-java-buildpack
    file: buildpack-pipeline/ci/updatebuildpack/updatebuildpack.yml
    params:
      BUILDPACK_NAME: java_buildpack
      DOWNLOADED_BUILDPACK_NAME: java-buildpack




- name: smoketest-sandbox
  public: true
  serial: true
  plan:
  - aggregate:
    - get: smoke-test
      resource: cf-smoke-test
    - get: gh-release-php-buildpack
      trigger: true
      passed: [php_buildpack_pcfdev]
    - get: gh-release-ruby-buildpack
      trigger: true
      passed: [ruby_buildpack_pcfdev]
    - get: gh-release-go-buildpack
      trigger: true
      passed: [go_buildpack_pcfdev]
    - get: gh-release-nodejs-buildpack
      trigger: true
      passed: [nodejs_buildpack_pcfdev]
    - get: gh-release-python-buildpack
      trigger: true
      passed: [python_buildpack_pcfdev]
    - get: gh-release-staticfile-buildpack
      trigger: true
      passed: [staticfile_buildpack_pcfdev]
    - get: gh-release-binary-buildpack
      trigger: true
      passed: [binary_buildpack_pcfdev]
    - get: gh-release-java-buildpack
      trigger: true
      passed: [java_buildpack_pcfdev]
    - get: env-info
      resource: gh-env-config-pcfdev
      trigger: true
    - get: buildpack-pipeline
  - task: smoke-test
    file: buildpack-pipeline/ci/smoketest/smoketest.yml 


- name: acceptance-sandbox
  public: true
  serial: true
  plan:
  - aggregate:
    - get: acceptance-tests
      resource: cf-acceptance-tests
      trigger: true
    - get: gh-release-php-buildpack
      trigger: true
      passed: [php_buildpack_pcfdev,smoketest-sandbox]
    - get: gh-release-ruby-buildpack
      trigger: true
      passed: [ruby_buildpack_pcfdev,smoketest-sandbox]
    - get: gh-release-go-buildpack
      trigger: true
      passed: [go_buildpack_pcfdev,smoketest-sandbox]
    - get: gh-release-nodejs-buildpack
      trigger: true
      passed: [nodejs_buildpack_pcfdev,smoketest-sandbox]
    - get: gh-release-python-buildpack
      trigger: true
      passed: [python_buildpack_pcfdev,smoketest-sandbox]
    - get: gh-release-staticfile-buildpack
      trigger: true
      passed: [staticfile_buildpack_pcfdev,smoketest-sandbox]
    - get: gh-release-binary-buildpack
      trigger: true
      passed: [binary_buildpack_pcfdev,smoketest-sandbox]
    - get: gh-release-java-buildpack
      trigger: true
      passed: [java_buildpack_pcfdev,smoketest-sandbox]
    - get: env-info
      resource: gh-env-config-pcfdev
      trigger: true
    - get: env-info
      resource: gh-env-config-pcfdev
      trigger: true
    - get: buildpack-pipeline
  - task: acceptance-tests
    file: buildpack-pipeline/ci/acceptancetests/acceptancetests.yml 



resources:
#php buildpack
- name: gh-release-php-buildpack
  type: github-release
  source:
    user: cloudfoundry
    repository: php-buildpack
    access_token: {{github-access-token}}

#ruby buildpack
- name: gh-release-ruby-buildpack
  type: github-release
  source:
    user: cloudfoundry
    repository: ruby-buildpack
    access_token: {{github-access-token}}

#go buildpack
- name: gh-release-go-buildpack
  type: github-release
  source:
    user: cloudfoundry
    repository: go-buildpack
    access_token: {{github-access-token}}

#nodejs buildpack
- name: gh-release-nodejs-buildpack
  type: github-release
  source:
    user: cloudfoundry
    repository: nodejs-buildpack
    access_token: {{github-access-token}}


#python buildpack
- name: gh-release-python-buildpack
  type: github-release
  source:
    user: cloudfoundry
    repository: python-buildpack
    access_token: {{github-access-token}}


#static buildpack
- name: gh-release-staticfile-buildpack
  type: github-release
  source:
    user: cloudfoundry
    repository: staticfile-buildpack
    access_token: {{github-access-token}}

#binary buildpack
- name: gh-release-binary-buildpack
  type: github-release
  source:
    user: cloudfoundry
    repository: binary-buildpack
    access_token: {{github-access-token}}

#binary buildpack
- name: gh-release-java-buildpack
  type: github-release
  source:
    user: cloudfoundry
    repository: java-buildpack
    access_token: {{github-access-token}}


#Env Resource pcfdev
- name: gh-env-config-pcfdev
  type: git
  source:
    uri: git@github.com:shinji62/env-config.git
    branch: pcfdev
    private_key: {{private-key-github-concourse}}

#This buildpack piepline
- name: buildpack-pipeline
  type: git
  source:
    uri: git@github.com:shinji62/buildpack-pipeline.git
    branch: master
    private_key: {{private-key-github-concourse}}


#Cloudfoundry /smoke test
- name: cf-smoke-test
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-smoke-tests.git
    branch: master
    private_key: {{private-key-github-concourse}}



#Cloudfoundry / Acceptance test
- name: cf-acceptance-tests
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-acceptance-tests.git
    branch: master
    private_key: {{private-key-github-concourse}}





