jobs:
- name: php_buildpack_pcfdev
  public: true
  serial: true
  plan:
  - aggregate:
    - get: buildpack-github-release
      resource: gh-release-php-buildpack
      trigger: true
    - get: env-info
      resource: gh-env-config-pcfdev
      trigger: true
    - get: buildpack-pipeline
  - task:
    file:  buildpack-pipeline/ci/updatebuildpack/updatebuildpack
    params:
      BUILDPACK_NAME=php_buildpack


- name: smoketest-sandbox
  public: true
  serial: true
  plan:
  - aggregate:
    - get: smoke-test
      resource: cf-smoke-test
    - get: gh-release-php-buildpack
      trigger: true
      passed: [php_buildpack]
    - get: env-info
      resource: gh-env-config-pcfdev
      trigger: true
    - get: buildpack-pipeline
  - task: smoke-test
    file: buildpack-pipeline/ci/smoketest/smoketest.yml 


  




resources:
#php buildpack
- name: gh-release-php-buildpack
  type: github-release
  source:
    user: cloudfoundry
    repository: php-buildpack
    access_token: {{github-access-token}}

#Env Resource pcfdev
- name: gh-env-config-pcfdev
  type: git
  source:
    uri: git@github.com:shinji62/env-config.git
    branch: pcfdev
    private_key: {{private-key-github-concourse}}

#This buildpack piepline
- name: buildpack-pipeline
  type: git
  source:
    uri: git@github.com:shinji62/buildpack-pipeline.git
    branch: master
    private_key: {{private-key-github-concourse}}


#Cloudfoundry /smoke test
- name: cf-smoke-test
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-smoke-tests.git
    branch: master
    private_key: {{private-key-github-concourse}}

    




